// Code generated by entc, DO NOT EDIT.

package product

const (
	// Label holds the string label denoting the product type in the database.
	Label = "product"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldProductName holds the string denoting the product_name field in the database.
	FieldProductName = "product_name"
	// FieldProductCost holds the string denoting the product_cost field in the database.
	FieldProductCost = "product_cost"

	// EdgeProducts holds the string denoting the products edge name in mutations.
	EdgeProducts = "products"

	// Table holds the table name of the product in the database.
	Table = "products"
	// ProductsTable is the table the holds the products relation/edge.
	ProductsTable = "bills"
	// ProductsInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	ProductsInverseTable = "bills"
	// ProductsColumn is the table column denoting the products relation/edge.
	ProductsColumn = "product_id"
)

// Columns holds all SQL columns for product fields.
var Columns = []string{
	FieldID,
	FieldProductName,
	FieldProductCost,
}

var (
	// ProductNameValidator is a validator for the "product_name" field. It is called by the builders before save.
	ProductNameValidator func(string) error
	// ProductCostValidator is a validator for the "product_cost" field. It is called by the builders before save.
	ProductCostValidator func(int) error
)
