// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"github.com/NoT-Ton/app/ent/bill"
	"github.com/NoT-Ton/app/ent/customer"
	"github.com/NoT-Ton/app/ent/product"
	"github.com/NoT-Ton/app/ent/user"
	"github.com/facebookincubator/ent/dialect/sql/sqlgraph"
	"github.com/facebookincubator/ent/schema/field"
)

// BillCreate is the builder for creating a Bill entity.
type BillCreate struct {
	config
	mutation *BillMutation
	hooks    []Hook
}

// SetQuantity sets the quantity field.
func (bc *BillCreate) SetQuantity(i int) *BillCreate {
	bc.mutation.SetQuantity(i)
	return bc
}

// SetAddedTime sets the added_time field.
func (bc *BillCreate) SetAddedTime(t time.Time) *BillCreate {
	bc.mutation.SetAddedTime(t)
	return bc
}

// SetNillableAddedTime sets the added_time field if the given value is not nil.
func (bc *BillCreate) SetNillableAddedTime(t *time.Time) *BillCreate {
	if t != nil {
		bc.SetAddedTime(*t)
	}
	return bc
}

// SetProductID sets the product edge to Product by id.
func (bc *BillCreate) SetProductID(id int) *BillCreate {
	bc.mutation.SetProductID(id)
	return bc
}

// SetNillableProductID sets the product edge to Product by id if the given value is not nil.
func (bc *BillCreate) SetNillableProductID(id *int) *BillCreate {
	if id != nil {
		bc = bc.SetProductID(*id)
	}
	return bc
}

// SetProduct sets the product edge to Product.
func (bc *BillCreate) SetProduct(p *Product) *BillCreate {
	return bc.SetProductID(p.ID)
}

// SetUserID sets the user edge to User by id.
func (bc *BillCreate) SetUserID(id int) *BillCreate {
	bc.mutation.SetUserID(id)
	return bc
}

// SetNillableUserID sets the user edge to User by id if the given value is not nil.
func (bc *BillCreate) SetNillableUserID(id *int) *BillCreate {
	if id != nil {
		bc = bc.SetUserID(*id)
	}
	return bc
}

// SetUser sets the user edge to User.
func (bc *BillCreate) SetUser(u *User) *BillCreate {
	return bc.SetUserID(u.ID)
}

// SetCustomerID sets the customer edge to Customer by id.
func (bc *BillCreate) SetCustomerID(id int) *BillCreate {
	bc.mutation.SetCustomerID(id)
	return bc
}

// SetNillableCustomerID sets the customer edge to Customer by id if the given value is not nil.
func (bc *BillCreate) SetNillableCustomerID(id *int) *BillCreate {
	if id != nil {
		bc = bc.SetCustomerID(*id)
	}
	return bc
}

// SetCustomer sets the customer edge to Customer.
func (bc *BillCreate) SetCustomer(c *Customer) *BillCreate {
	return bc.SetCustomerID(c.ID)
}

// Mutation returns the BillMutation object of the builder.
func (bc *BillCreate) Mutation() *BillMutation {
	return bc.mutation
}

// Save creates the Bill in the database.
func (bc *BillCreate) Save(ctx context.Context) (*Bill, error) {
	if _, ok := bc.mutation.Quantity(); !ok {
		return nil, &ValidationError{Name: "quantity", err: errors.New("ent: missing required field \"quantity\"")}
	}
	if v, ok := bc.mutation.Quantity(); ok {
		if err := bill.QuantityValidator(v); err != nil {
			return nil, &ValidationError{Name: "quantity", err: fmt.Errorf("ent: validator failed for field \"quantity\": %w", err)}
		}
	}
	if _, ok := bc.mutation.AddedTime(); !ok {
		v := bill.DefaultAddedTime()
		bc.mutation.SetAddedTime(v)
	}
	var (
		err  error
		node *Bill
	)
	if len(bc.hooks) == 0 {
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BillMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			bc.mutation = mutation
			node, err = bc.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BillCreate) SaveX(ctx context.Context) *Bill {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (bc *BillCreate) sqlSave(ctx context.Context) (*Bill, error) {
	b, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if cerr, ok := isSQLConstraintError(err); ok {
			err = cerr
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	b.ID = int(id)
	return b, nil
}

func (bc *BillCreate) createSpec() (*Bill, *sqlgraph.CreateSpec) {
	var (
		b     = &Bill{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: bill.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: bill.FieldID,
			},
		}
	)
	if value, ok := bc.mutation.Quantity(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeInt,
			Value:  value,
			Column: bill.FieldQuantity,
		})
		b.Quantity = value
	}
	if value, ok := bc.mutation.AddedTime(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: bill.FieldAddedTime,
		})
		b.AddedTime = value
	}
	if nodes := bc.mutation.ProductIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.ProductTable,
			Columns: []string{bill.ProductColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: product.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.UserTable,
			Columns: []string{bill.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: user.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.CustomerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   bill.CustomerTable,
			Columns: []string{bill.CustomerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: customer.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return b, _spec
}
