// Code generated by entc, DO NOT EDIT.

package customer

const (
	// Label holds the string label denoting the customer type in the database.
	Label = "customer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCustomerName holds the string denoting the customer_name field in the database.
	FieldCustomerName = "customer_name"

	// EdgeBuys holds the string denoting the buys edge name in mutations.
	EdgeBuys = "buys"

	// Table holds the table name of the customer in the database.
	Table = "customers"
	// BuysTable is the table the holds the buys relation/edge.
	BuysTable = "bills"
	// BuysInverseTable is the table name for the Bill entity.
	// It exists in this package in order to avoid circular dependency with the "bill" package.
	BuysInverseTable = "bills"
	// BuysColumn is the table column denoting the buys relation/edge.
	BuysColumn = "customer_id"
)

// Columns holds all SQL columns for customer fields.
var Columns = []string{
	FieldID,
	FieldCustomerName,
}

var (
	// CustomerNameValidator is a validator for the "customer_name" field. It is called by the builders before save.
	CustomerNameValidator func(string) error
)
