/* tslint:disable */
/* eslint-disable */
/**
 * SUT SA Example API
 * This is a sample server for SUT SE 2563
 *
 * The version of the OpenAPI document: 1.0
 * Contact: support@swagger.io
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ControllersBill
 */
export interface ControllersBill {
    /**
     * 
     * @type {string}
     * @memberof ControllersBill
     */
    addtime?: string;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    customerID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    productID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    quantityID?: number;
    /**
     * 
     * @type {number}
     * @memberof ControllersBill
     */
    userID?: number;
}

export function ControllersBillFromJSON(json: any): ControllersBill {
    return ControllersBillFromJSONTyped(json, false);
}

export function ControllersBillFromJSONTyped(json: any, ignoreDiscriminator: boolean): ControllersBill {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'addtime': !exists(json, 'addtime') ? undefined : json['addtime'],
        'customerID': !exists(json, 'customerID') ? undefined : json['customerID'],
        'productID': !exists(json, 'productID') ? undefined : json['productID'],
        'quantityID': !exists(json, 'quantityID') ? undefined : json['quantityID'],
        'userID': !exists(json, 'userID') ? undefined : json['userID'],
    };
}

export function ControllersBillToJSON(value?: ControllersBill | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'addtime': value.addtime,
        'customerID': value.customerID,
        'productID': value.productID,
        'quantityID': value.quantityID,
        'userID': value.userID,
    };
}


