// Code generated by entc, DO NOT EDIT.

package bill

import (
	"time"
)

const (
	// Label holds the string label denoting the bill type in the database.
	Label = "bill"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldQuantity holds the string denoting the quantity field in the database.
	FieldQuantity = "quantity"
	// FieldAddedTime holds the string denoting the added_time field in the database.
	FieldAddedTime = "added_time"

	// EdgeProduct holds the string denoting the product edge name in mutations.
	EdgeProduct = "product"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// EdgeCustomer holds the string denoting the customer edge name in mutations.
	EdgeCustomer = "customer"

	// Table holds the table name of the bill in the database.
	Table = "bills"
	// ProductTable is the table the holds the product relation/edge.
	ProductTable = "bills"
	// ProductInverseTable is the table name for the Product entity.
	// It exists in this package in order to avoid circular dependency with the "product" package.
	ProductInverseTable = "products"
	// ProductColumn is the table column denoting the product relation/edge.
	ProductColumn = "product_id"
	// UserTable is the table the holds the user relation/edge.
	UserTable = "bills"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
	// CustomerTable is the table the holds the customer relation/edge.
	CustomerTable = "bills"
	// CustomerInverseTable is the table name for the Customer entity.
	// It exists in this package in order to avoid circular dependency with the "customer" package.
	CustomerInverseTable = "customers"
	// CustomerColumn is the table column denoting the customer relation/edge.
	CustomerColumn = "customer_id"
)

// Columns holds all SQL columns for bill fields.
var Columns = []string{
	FieldID,
	FieldQuantity,
	FieldAddedTime,
}

// ForeignKeys holds the SQL foreign-keys that are owned by the Bill type.
var ForeignKeys = []string{
	"customer_id",
	"product_id",
	"user_id",
}

var (
	// QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	QuantityValidator func(int) error
	// DefaultAddedTime holds the default value on creation for the added_time field.
	DefaultAddedTime func() time.Time
)
